simclr:
  train:
    batch_size: 512
    num_workers: 8
    start_epoch: 0
    epochs: 100
    restart_log_dir_path: ""
    data_dir_path: "/data"
    dataset: "CIFAR10"
    save_num_epochs: 1
    img_size: 32
    optimizer: "Adam"
    weight_decay: 1.0e-6
    temperature: 0.1


  model:
    resnet: "resnet18"
    normalize: True
    projection_dim: 64

logistic_regression:
  epochs: 100           
  learning_rate: 0.001
  batch_size: 512
  momentum: 0.9
  img_size: 32
  
fine_tuning:
  learning_rate: 0.001
  batch_size: 512
  momentum: 0.9
  step_size: 100
  gamma: 0.1
  epochs: 10
  img_size: 32
  save_num_epochs: 1

onnx:
  batch_size: 512
  img_size: 32
